### ISSUE TITLE
why use dart 3.6,dont running in dart 3.5

### ISSUE THREAD

**Issue by wangcker** [bdero/flutter_scene#10]
as subject

**Comment by bdero** [comment]
Because this package relies on Native Assets build hooks, which is an experimental Dart feature.

So I am restricted from publishing new versions of this package without a Dart 3.6 constraint.

```
Do you want to publish flutter_scene 0.2.0 to https://pub.dev (y/N)? y
Uploading... (1.8s)
Message from server: `hook/build.dart` is allowed only with a minimum SDK constraint of `3.6.0-0`.
```
