### ISSUE TITLE
Importer compilation errors with Clang 10 - Ubuntu 20

### ISSUE THREAD

**Issue by jwinarske** [bdero/flutter_scene#14]
Running on Ubuntu 20 (Clang 10) it fails to compile with:
[clang_10_scene_importer.txt](https://github.com/user-attachments/files/16691978/clang_10_scene_importer.txt)

**Comment by bdero** [comment]
Whoops, looks like it's not as portable as I thought it was. Do you also happen to use Clang 10 for compiling Flutter Engine BTW?

**Comment by jwinarske** [comment]
@bdero for the engine (x86_64, arm, arm64) I use the built in toolchain, and for riscv64 an enhanced external clang 18

**Comment by bdero** [comment]
@jwinarske flutter_scene 0.5.0-0 and flutter_scene_importer 0.2.0-0 have some fixes to make the compilation more portable here. I also landed fixes recently for the GL backend in Flutter GPU, so I'm hoping this package can run in your setup now.

Would love it if you could give it a try. :) I'll close this issue for the moment, but let's re-open it if you still run into issues.

**Comment by jwinarske** [comment]
I'll test it out when I'm back in next week

**Comment by bdero** [comment]
@jwinarske Let me know if you get a chance to try this out. I'm interested in helping you get it working (and to land missing features or solve rendering bugs for your use case).
We're planning to make a lot more progress on rendering and interactivity features this package. :)

**Comment by jwinarske** [comment]
Will get to by Monday!
