### ISSUE TITLE
Need 360° Free Orbit Rotation for 3D Model in All Directions Without Constraints

### ISSUE THREAD

**Issue by RajatDBazaar** [bdero/flutter_scene#33]
I am developing a 3D model rendering app using Flutter with model-viewer, and everything is working well except for one issue. We need our model to rotate freely in 360° in all directions without restrictions. Currently, the model rotates infinitely on the horizontal axis, but vertically, it is limited to 180°, causing the rotation to lock beyond that point.

What we're aiming for is trackball-style movement, but right now, we only have turntable-style movement. We've been trying various methods to resolve this issue for the past 3 weeks without success, and we're feeling quite exhausted. Any help or suggestions would be greatly appreciated.

Like this website has -- https://app.emb3d.com/3dviewer [View Point - Trackball]

**Comment by bdero** [comment]
Hi, this is the repository for the `flutter_scene` package. Correct me if I'm wrong, but it sounds like you're using another package that I have no authorship or control over, so I won't be able to help you with that here. Sorry.

Trackball-style motion can be done with `flutter_scene` by capturing incremental swipe gestures from the `GestureDetector` widget, converting those gestures into `vector_math` quaternions, and multiplying them into the model's transformation matrix.

**Comment by RajatDBazaar** [comment]
Can you give me a detailed guide on how I can achieve it using `flutter_scene` !!
