### ISSUE TITLE
Is this package stable for simple task such as render GLTF, GLB model and change it textures by code?

### ISSUE THREAD

**Issue by HuyNguyen1590** [bdero/flutter_scene#45]
I'm really excited about 3D in Flutter. My task requires a simple function to render GLTF and GLB models and add custom textures to them. Is this package stable enough to complete this task? So I will import and study how to use it right now.

**Comment by bdero** [comment]
Hi! Please see [this comment](https://github.com/bdero/flutter_scene/issues/23#issuecomment-2362834321) for guidance on how to access imported materials and replace textures.
