### ISSUE TITLE
Emissive parameter in physically_based_material has no effect

### ISSUE THREAD

**Issue by mrusiniak** [bdero/flutter_scene#46]
Hi, 
First of all thank you for your very hard work!
I think flutter_scene is great!!

I am trying to render a sphere that glows. 
I checked the shaders, checked material and everything seems to be prepared to be working with emissive textures and factor. However I am not able to generate glow effect. 

It is also possible that I missunderdand the usage of it - is the preprocessing not defined for bloom or similar effect defined yet?

**Comment by mrusiniak** [comment]
here is the piece of code i am using to create it:
      final emissiveTexture = await fs.gpuTextureFromAsset('assets/textures/glow_texture.png');
      final transparentTexture = await fs.gpuTextureFromAsset('assets/textures/transparent_texture.png');
      final glowMaterial = PhysicallyBasedMaterial(
        emissiveTexture: emissiveTexture, // Apply the glow texture      
        //baseColorTexture: transparentTexture,  
      );
      
      glowMaterial.baseColorFactor=vm.Vector4(0.2, 0.2, 0.1, 0.5);
      glowMaterial.metallicFactor=0;
      glowMaterial.roughnessFactor=1;
      glowMaterial.emissiveFactor=vm.Vector4(1, 1, 1, 1);
      // Create a sphere for each brain region
      ElectrodeMapper.getAllRegions().forEach((region) async {
        final sphere = fs.Node(
          name: region,
          mesh: fs.Mesh(
            fs.SphereGeometry(0.3, 32, 32), // Smooth sphere with radius 0.05
            glowMaterial,
          ),
        );
        scene.add(sphere);
      }

      and custom painter
      
       @override
  void paint(Canvas canvas, Size size) {
    if (!isLoaded) {
      return; // Skip rendering if the model isn't loaded
    }

    // Create a camera that orbits around the model
    final camera = fs.PerspectiveCamera(
      position: vm.Vector3(
        zoom * cos(-rotationY) * cos(rotationX), // X-coordinate
        zoom * sin(rotationX),                  // Y-coordinate
        zoom * sin(-rotationY) * cos(rotationX), // Z-coordinate
      ),
      target: vm.Vector3(0, 0, 0), // Always look at the origin
    );
    // Set a background color (dark color to enhance the emissive effect)
    final paint = Paint()..color = Color(0xFF000000); // Black background
    canvas.drawRect(Rect.fromLTWH(0, 0, size.width, size.height), paint);
    scene.render(camera, canvas, viewport: Offset.zero & size);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;

**Comment by bdero** [comment]
Hi! Thanks for your question.

> It is also possible that I missunderdand the usage of it - is the preprocessing not defined for bloom or similar effect defined yet?

Yes, Scene does not have any post-processing effects yet. This is something we need to add, of course. I added an issue here: https://github.com/bdero/flutter_scene/issues/47
